version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://localhost/back

  backend:
    depends_on:
      - db
    build: ./backend
    environment:
      DB_URL: mongodb://db:27017/vidly
    command: [./docker-entrypoint.sh]

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  vidly:
